package se.inera.intyg.certificateservice.domain.action.model;

public enum CertificateActionType {
  CREATE, READ, UPDATE, DELETE, SIGN, SEND, PRINT, REVOKE, REPLACE, REPLACE_CONTINUE, RENEW, SEND_AFTER_SIGN, COMPLEMENT, CANNOT_COMPLEMENT, FORWARD_MESSAGE, HANDLE_COMPLEMENT, RECEIVE_COMPLEMENT
}
