#!groovy

def s2iWebhook = registerWebhook()
def build = ""

// run shell command, return status code
def shell(cmd) {
    sh(
            script: cmd,
            returnStatus: true
    )
}

// run shell command and signal an error on failure
def eshell(cmd) {
    def rc = shell(cmd)
    if (rc != 0) {
        error("Error: shell command exited with error code ${rc}")
    }
}

def log(msg) {
    echo "${new Date().format('yyyy-MM-dd HH:mm:ss.SSS')} : ${msg}"
}

pipeline {
    agent any

    stages {

        stage('Checkout Source') {
            steps {
                script {
                    git url: "https://github.com/sklintyg/core.git", branch: "main"
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                            def models = openshift.process("-f", "devops/openshift/buildtemplate-service.yaml",
                                    "-p", "IS_APP_NAME=customer-terminate-service",
                                    "-p", "APP_NAME=customer-terminate-service",
                                    "-p", "STAGE=test",
                                    "-p", "BUILD_VERSION=latest",
                                    "-p", "ARTIFACT_IMAGE_SUFFIX=artifact")
                            openshift.apply(models)

                            build = openshift.selector("bc", "customer-terminate-service-artifact").startBuild("--from-dir ./customer-terminate-service")
                            sleep(time: 1, unit: 'SECONDS')
                            log "${build.name()} started"

                            timeout(5) {
                                def status = ""
                                build.untilEach(1) {
                                    status = it.object().status.phase
                                    log "Build status: ${status}"
                                    return !["Running", "Pending", "New"].contains(status)
                                }

                                log "Logs for artifact build"
                                build.logs()
                                if (status != "Complete") {
                                    error("Build terminated with status: ${status}")
                                }
                                log "Build Completed"
                            }
                        }
                    }
                }
            }
        }

        stage('Build Runtime Image') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                            log "Build runtime image webcert-frontend"
                            build = openshift.selector("bc", "customer-terminate-service").startBuild()
                            sleep(time: 1, unit: 'SECONDS')
                            log "${build.name()} started"
                            timeout(5) {
                                def status = ""
                                build.untilEach(1) {
                                    status = it.object().status.phase
                                    log "Build status: ${status}"
                                    return !["Running", "Pending", "New"].contains(status)
                                }
                                log "Logs for docker runtime build"
                                build.logs()
                                if (status != "Complete") {
                                    error("Build terminated with status: ${status}")
                                }
                                log "Build Completed"
                            }
                        }
                    }
                }
            }
        }
    }

    post {
        success {
            script {
                log "Pipeline success :)"
                util.notifySuccess()
            }
        }

        failure {
            script {
                log "Pipeline Failed :("
                util.notifyFailed()
            }
        }

        cleanup {
            log "Clean up in post work space"
            cleanWs()
        }
    }
}
