package se.inera.intyg.certificateservice.domain.certificatemodel.model;

public enum ElementType {
  CATEGORY, DATE, ISSUING_UNIT, TEXT_AREA, CHECKBOX_DATE_RANGE_LIST, CHECKBOX_MULTIPLE_DATE,
  RADIO_MULTIPLE_CODE, RADIO_BOOLEAN, MESSAGE, DIAGNOSIS, TEXT_FIELD, MEDICAL_INVESTIGATION_LIST,
  CHECKBOX_MULTIPLE_CODE, VISUAL_ACUITIES, DROPDOWN, DATE_RANGE, CHECKBOX_BOOLEAN, INTEGER, ICF
}
