package se.inera.intyg.certificateservice.application.common.dto;

import se.inera.intyg.certificateservice.domain.action.certificate.model.CertificateActionType;
import se.inera.intyg.certificateservice.domain.message.model.MessageActionType;

public enum ResourceLinkTypeDTO {
  EDIT_CERTIFICATE,
  READ_CERTIFICATE,
  REMOVE_CERTIFICATE,
  FORWARD_CERTIFICATE,
  FORWARD_QUESTION,
  READY_FOR_SIGN,
  SIGN_CERTIFICATE,
  SEND_CERTIFICATE,
  REVOKE_CERTIFICATE,
  REPLACE_CERTIFICATE,
  REPLACE_CERTIFICATE_CONTINUE,
  RENEW_CERTIFICATE,
  PRINT_CERTIFICATE,
  COPY_CERTIFICATE,
  COPY_CERTIFICATE_CONTINUE,
  FMB,
  QUESTIONS,
  QUESTIONS_NOT_AVAILABLE,
  CREATE_QUESTIONS,
  ANSWER_QUESTION,
  HANDLE_QUESTION,
  COMPLEMENT_CERTIFICATE,
  CANNOT_COMPLEMENT_CERTIFICATE,
  CREATE_CERTIFICATE_FROM_TEMPLATE,
  CREATE_CERTIFICATE_FROM_CANDIDATE,
  CREATE_CERTIFICATE_FROM_CANDIDATE_WITH_MESSAGE,
  ACCESS_SEARCH_CREATE_PAGE,
  ACCESS_DRAFT_LIST,
  ACCESS_QUESTION_LIST,
  ACCESS_SIGNED_CERTIFICATES_LIST,
  LOG_OUT,
  CREATE_CERTIFICATE,
  CHOOSE_UNIT,
  CHANGE_UNIT,
  PRIVATE_PRACTITIONER_PORTAL,
  NAVIGATE_BACK_BUTTON,
  WARNING_NORMAL_ORIGIN,
  SUBSCRIPTION_WARNING,
  WARNING_DODSBEVIS_INTEGRATED,
  CREATE_DODSBEVIS_CONFIRMATION,
  CREATE_LUAENA_CONFIRMATION,
  WARNING_LUAENA_INTEGRATED,
  SIGN_CERTIFICATE_CONFIRMATION,
  DISPLAY_PATIENT_ADDRESS_IN_CERTIFICATE,
  MISSING_RELATED_CERTIFICATE_CONFIRMATION,
  SHOW_RELATED_CERTIFICATE,
  SRS_FULL_VIEW,
  SRS_MINIMIZED_VIEW,
  SEND_AFTER_SIGN_CERTIFICATE,
  CANNOT_COMPLEMENT_CERTIFICATE_ONLY_MESSAGE,
  QUESTIONS_ADMINISTRATIVE,
  FORWARD_CERTIFICATE_FROM_LIST,
  INACTIVE_CERTIFICATE;

  public static ResourceLinkTypeDTO toResourceLinkType(CertificateActionType type) {
    return switch (type) {
      case CREATE -> CREATE_CERTIFICATE;
      case READ -> READ_CERTIFICATE;
      case UPDATE -> EDIT_CERTIFICATE;
      case DELETE -> REMOVE_CERTIFICATE;
      case SIGN -> SIGN_CERTIFICATE;
      case SEND -> SEND_CERTIFICATE;
      case PRINT -> PRINT_CERTIFICATE;
      case REVOKE -> REVOKE_CERTIFICATE;
      case REPLACE -> REPLACE_CERTIFICATE;
      case REPLACE_CONTINUE -> REPLACE_CERTIFICATE_CONTINUE;
      case RENEW -> RENEW_CERTIFICATE;
      case SEND_AFTER_SIGN, SEND_AFTER_COMPLEMENT -> SEND_AFTER_SIGN_CERTIFICATE;
      case COMPLEMENT -> COMPLEMENT_CERTIFICATE;
      case CANNOT_COMPLEMENT -> CANNOT_COMPLEMENT_CERTIFICATE_ONLY_MESSAGE;
      case FORWARD_MESSAGE -> FORWARD_QUESTION;
      case HANDLE_COMPLEMENT, HANDLE_MESSAGE -> HANDLE_QUESTION;
      case MESSAGES -> QUESTIONS;
      case MESSAGES_ADMINISTRATIVE -> QUESTIONS_ADMINISTRATIVE;
      case CREATE_MESSAGE -> CREATE_QUESTIONS;
      case ANSWER_MESSAGE -> ANSWER_QUESTION;
      case FORWARD_CERTIFICATE -> FORWARD_CERTIFICATE;
      case READY_FOR_SIGN -> READY_FOR_SIGN;
      case QUESTIONS_NOT_AVAILABLE -> QUESTIONS_NOT_AVAILABLE;
      case FORWARD_CERTIFICATE_FROM_LIST -> FORWARD_CERTIFICATE_FROM_LIST;
      case FMB -> FMB;
      case SRS_DRAFT -> SRS_FULL_VIEW;
      case SRS_SIGNED -> SRS_MINIMIZED_VIEW;
      case CREATE_DRAFT_FROM_CERTIFICATE -> CREATE_CERTIFICATE_FROM_TEMPLATE;
      case UPDATE_DRAFT_FROM_CERTIFICATE -> CREATE_CERTIFICATE_FROM_CANDIDATE;
      case INACTIVE_CERTIFICATE_MODEL -> INACTIVE_CERTIFICATE;
      case RECEIVE_COMPLEMENT, RECEIVE_ANSWER, RECEIVE_QUESTION, RECEIVE_REMINDER, SAVE_MESSAGE,
           DELETE_MESSAGE, SEND_MESSAGE, SAVE_ANSWER, DELETE_ANSWER, SEND_ANSWER,
           LIST_CERTIFICATE_TYPE ->
          throw new IllegalArgumentException("%s is not a valid type!".formatted(type));
    };
  }

  public static ResourceLinkTypeDTO toResourceLinkType(MessageActionType type) {
    return switch (type) {
      case ANSWER -> ANSWER_QUESTION;
      case COMPLEMENT -> COMPLEMENT_CERTIFICATE;
      case FORWARD -> FORWARD_QUESTION;
      case CANNOT_COMPLEMENT -> CANNOT_COMPLEMENT_CERTIFICATE_ONLY_MESSAGE;
      case HANDLE_COMPLEMENT, HANDLE_MESSAGE -> HANDLE_QUESTION;
    };
  }
}