package se.inera.intyg.certificateservice.application.certificate.dto.validation;

public enum CertificateDataValidationType {
  SHOW_VALIDATION, HIDE_VALIDATION, MAX_DATE_VALIDATION, MIN_DATE_VALIDATION, TEXT_VALIDATION, ENABLE_VALIDATION,
  DISABLE_VALIDATION, MANDATORY_VALIDATION, AUTO_FILL_VALIDATION, DISABLE_SUB_ELEMENT_VALIDATION, CATEGORY_MANDATORY_VALIDATION,
  HIGHLIGHT_VALIDATION
}
