package se.inera.intyg.certificateservice.application.certificate.dto.validation;

public enum CertificateDataValidationType {
  MANDATORY_VALIDATION, SHOW_VALIDATION, TEXT_VALIDATION, DISABLE_VALIDATION, DISABLE_SUB_ELEMENT_VALIDATION, CATEGORY_MANDATORY_VALIDATION, HIDE_VALIDATION, AUTO_FILL_VALIDATION
}