kind: Template
apiVersion: v1
metadata:
  name: buildtemplate-frontend
parameters:
  - name: APP_NAME
    required: true
    value: "customer-terminate-service"
  - name: IS_APP_NAME
    required: true
    value: "customer-terminate-service"
  - name: ARTIFACT_IMAGE_SUFFIX
    required: true
    value: "artifact"
  - name: STAGE
    required: true
    value: "test"
  - name: BUILD_VERSION
    required: true
    value: "latest"
  - name: E_UID
    value: "1000310000"
    required: true
  - name: BUILDER_IMAGE
    required: true
    value: "s2i-service-builder:latest"
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      name: ${APP_NAME}-${ARTIFACT_IMAGE_SUFFIX}
      labels:
        app: ${APP_NAME}
        stage: ${STAGE}
    spec:
      completionDeadlineSeconds: 1200
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 4
      output:
        to:
          kind: ImageStreamTag
          name: ${IS_APP_NAME}-${ARTIFACT_IMAGE_SUFFIX}:${BUILD_VERSION}
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 200m
          memory: 2Gi
      source:
        contextDir: /
        type: Binary
      strategy:
        sourceStrategy:
          env:
            - name: APP_NAME
              value: ${APP_NAME}
            - name: STAGE
              value: ${STAGE}
            - name: BUILD_VERSION
              value: ${BUILD_VERSION}
            - name: BUILDER_IMAGE
              value: ${BUILDER_IMAGE}
          from:
            kind: "ImageStreamTag"
            name: ${BUILDER_IMAGE}
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
        stage: ${STAGE}
    spec:
      completionDeadlineSeconds: 600
      successfulBuildsHistoryLimit: 4
      failedBuildsHistoryLimit: 4
      output:
        to:
          kind: ImageStreamTag
          name: ${IS_APP_NAME}:${BUILD_VERSION}
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 200m
          memory: 2Gi
      source:
        dockerfile: |-
          FROM service-base:latest
          ENV APP_NAME=${APP_NAME}
          ADD ROOT.jar /deployments/
        images:
          - from:
              kind: ImageStreamTag
              name: ${IS_APP_NAME}-${ARTIFACT_IMAGE_SUFFIX}:${BUILD_VERSION}
            paths:
              - sourcePath: /tmp/artifacts/.
                destinationDir: "."
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: service-base:latest
        type: Docker
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${IS_APP_NAME}-${ARTIFACT_IMAGE_SUFFIX}
      labels:
        app: ${IS_APP_NAME}
        stage: ${STAGE}
    spec:
      lookupPolicy:
        local: true
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${IS_APP_NAME}
      labels:
        app: ${IS_APP_NAME}
        stage: ${STAGE}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${IS_APP_NAME}-verified
      labels:
        app: ${IS_APP_NAME}
        stage: ${STAGE}
    spec:
      lookupPolicy:
        local: false
