### Get certificatetypeinfo
POST http://localhost:18030/api/certificatetypeinfo
Content-Type: application/json

{
  "user": {
    "id": "TSTNMT2321000156-DRAA",
    "role": "DOCTOR",
    "blocked": "false"
  },
  "unit": {
    "id": "TSTNMT2321000156-ALHM",
    "name": "Alfa Hudmottagningen",
    "inactive": "false"
  },
  "careUnit": {
    "id": "TSTNMT2321000156-ALMC",
    "name": "Alfa Medicincentrum"
  },
  "careProvider": {
    "id": "TSTNMT2321000156-ALFA",
    "name": "Alfa Regionen"
  },
  "patient": {
    "id": {
      "type": "PERSONAL_IDENTITY_NUMBER",
      "id": "191212121212"
    },
    "deceased": "false",
    "protectedPerson": "false",
    "testIndicated": "false"
  }
}

### Get latest version
GET http://localhost:18030/api/certificatetypeinfo/fk7210/exists
Content-Type: application/json