### Create certificate - Hudmottagningen
POST http://localhost:18030/api/certificate
Content-Type: application/json

{
  "user": {
    "id": "TSTNMT2321000156-DRAA",
    "name": "Alja Doctor",
    "role": "DOCTOR",
    "blocked": "false"
  },
  "unit": {
    "id": "TSTNMT2321000156-ALHM",
    "name": "Alfa Hudmottagningen",
    "address": "Alfaadressen 1",
    "city": "Alfastaden",
    "zipCode": "Alfapostnummer",
    "inactive": "false"
  },
  "careUnit": {
    "id": "TSTNMT2321000156-ALMC",
    "name": "Alfa Medicincentrum",
    "address": "Alfaadressen 1",
    "city": "Alfastaden",
    "zipCode": "Alfapostnummer",
    "inactive": "false"
  },
  "careProvider": {
    "id": "TSTNMT2321000156-ALFA",
    "name": "Alfa Regionen"
  },
  "patient": {
    "id": {
      "type": "PERSONAL_IDENTITY_NUMBER",
      "id": "191212121212"
    },
    "firstName": "Tolvan",
    "middleName": "TP",
    "lastName": "Tolvansson",
    "fullName": "Tolvan TP Tolvansson",
    "deceased": "false",
    "protectedPerson": "false",
    "testIndicated": "false"
  },
  "certificateModelId": {
    "type": "fk7211",
    "version": "1.0"
  }
}

### Create certificate - Allergimottagningen
POST http://localhost:18030/api/certificate
Content-Type: application/json

{
  "user": {
    "id": "TSTNMT2321000156-DRAA",
    "name": "Alja Doctor",
    "role": "DOCTOR",
    "blocked": "false"
  },
  "unit": {
    "id": "TSTNMT2321000156-ALAM",
    "name": "Alfa Allergimottagningen",
    "address": "Alfaadressen 1",
    "city": "Alfastaden",
    "zipCode": "Alfapostnummer",
    "inactive": "false"
  },
  "careUnit": {
    "id": "TSTNMT2321000156-ALMC",
    "name": "Alfa Medicincentrum",
    "address": "Alfaadressen 1",
    "city": "Alfastaden",
    "zipCode": "Alfapostnummer",
    "inactive": "false"
  },
  "careProvider": {
    "id": "TSTNMT2321000156-ALFA",
    "name": "Alfa Regionen"
  },
  "patient": {
    "id": {
      "type": "PERSONAL_IDENTITY_NUMBER",
      "id": "191212121212"
    },
    "firstName": "Tolvan",
    "middleName": "TP",
    "lastName": "Tolvansson",
    "fullName": "Tolvan TP Tolvansson",
    "deceased": "false",
    "protectedPerson": "false",
    "testIndicated": "false"
  },
  "certificateModelId": {
    "type": "fk7211",
    "version": "1.0"
  }
}

### Certificate exists
GET http://localhost:18030/api/certificate/87ee572b-f55d-4955-b7a0-cb60d5e7be45/exists

### Get certificate
POST http://localhost:18030/api/certificate/87ee572b-f55d-4955-b7a0-cb60d5e7be45
Content-Type: application/json

{
  "user": {
    "id": "TSTNMT2321000156-DRAA",
    "name": "Alja Doctor",
    "role": "DOCTOR",
    "blocked": "false"
  },
  "unit": {
    "id": "TSTNMT2321000156-ALHM",
    "name": "Alfa Hudmottagningen",
    "address": "Alfaadressen 1",
    "city": "Alfastaden",
    "zipCode": "Alfapostnummer",
    "inactive": "false"
  },
  "careUnit": {
    "id": "TSTNMT2321000156-ALMC",
    "name": "Alfa Medicincentrum"
  },
  "careProvider": {
    "id": "TSTNMT2321000156-ALFA",
    "name": "Alfa Regionen"
  },
  "patient": {
    "id": {
      "type": "PERSONAL_IDENTITY_NUMBER",
      "id": "191212121212"
    },
    "firstName": "Tolvan",
    "middleName": "TP",
    "lastName": "Tolvansson",
    "fullName": "Tolvan TP Tolvansson",
    "deceased": "false",
    "protectedPerson": "false",
    "testIndicated": "false",
    "street": "",
    "zipcode": "",
    "city": ""
  }
}

### Update certificate
PUT http://localhost:18030/api/certificate/87ee572b-f55d-4955-b7a0-cb60d5e7be45
Content-Type: application/json

{
  "user": {
    "id": "TSTNMT2321000156-DRAA",
    "name": "Alja Doctor",
    "role": "DOCTOR",
    "blocked": "false"
  },
  "unit": {
    "id": "TSTNMT2321000156-ALHM",
    "name": "Alfa Hudmottagningen",
    "address": "Alfaadressen 1",
    "city": "Alfastaden",
    "zipCode": "Alfapostnummer",
    "inactive": "false"
  },
  "careUnit": {
    "id": "TSTNMT2321000156-ALMC",
    "name": "Alfa Medicincentrum"
  },
  "careProvider": {
    "id": "TSTNMT2321000156-ALFA",
    "name": "Alfa Regionen"
  },
  "patient": {
    "id": {
      "type": "PERSONAL_IDENTITY_NUMBER",
      "id": "191212121212"
    },
    "firstName": "Tolvan",
    "middleName": "TP",
    "lastName": "Tolvansson",
    "fullName": "Tolvan TP Tolvansson",
    "deceased": "false",
    "protectedPerson": "false",
    "testIndicated": "false",
    "street": "",
    "zipcode": "",
    "city": ""
  },
  "certificate": {
    "metadata": {
      "id": "5246e783-cfaa-4604-8d56-8923228ad096",
      "type": "fk7211",
      "typeVersion": "1.0",
      "typeName": "fk7211",
      "name": "Intyg om graviditet",
      "description": "Intyg om graviditet Ungefär i vecka 20 får du ett intyg om graviditet av barnmorskan. Intyget anger också datum för beräknad förlossning. Intyget skickar du till Försäkringskassan, som ger besked om kommande föräldrapenning.",
      "created": "2024-02-14T08:37:07",
      "status": "UNSIGNED",
      "testCertificate": false,
      "forwarded": false,
      "sent": false,
      "sentTo": null,
      "relations": {
        "parent": null,
        "children": null
      },
      "unit": {
        "unitId": "TSTNMT2321000156-ALHM",
        "unitName": "Alfa Hudmottagningen",
        "address": "Alfaadressen 1",
        "zipCode": "Alfapostnummer",
        "city": "Alfastaden",
        "phoneNumber": "009911",
        "email": null,
        "isInactive": false
      },
      "careUnit": {
        "unitId": "TSTNMT2321000156-ALMC",
        "unitName": "Alfa Medicincentrum",
        "address": null,
        "zipCode": null,
        "city": null,
        "phoneNumber": null,
        "email": null,
        "isInactive": null
      },
      "careProvider": {
        "unitId": "TSTNMT2321000156-ALFA",
        "unitName": "Alfa Regionen",
        "address": null,
        "zipCode": null,
        "city": null,
        "phoneNumber": null,
        "email": null,
        "isInactive": null
      },
      "patient": {
        "personId": {
          "type": "PERSONAL_IDENTITY_NUMBER",
          "id": "191212121212"
        },
        "previousPersonId": null,
        "firstName": "Tolvan",
        "lastName": "Tolvansson",
        "middleName": "TP",
        "fullName": "Tolvan TP Tolvansson",
        "street": "",
        "city": "",
        "zipCode": "",
        "coordinationNumber": null,
        "testIndicated": false,
        "protectedPerson": false,
        "deceased": false,
        "differentNameFromEHR": null,
        "personIdChanged": null,
        "reserveId": null,
        "addressFromPU": null
      },
      "issuedBy": {
        "personId": "TSTNMT2321000156-DRAA",
        "fullName": "Alja Doctor",
        "prescriptionCode": null
      },
      "version": 1,
      "latestMajorVersion": true,
      "readyForSign": null,
      "responsibleHospName": null,
      "recipient": null,
      "summary": null
    },
    "data": {
      "FRG_1": {
        "id": "FRG_1",
        "parent": "KAT_1",
        "index": 2,
        "config": {
          "type": "UE_DATE",
          "type": "UE_DATE",
          "header": null,
          "label": null,
          "icon": null,
          "text": "Beräknat nedkomstdatum",
          "description": null,
          "accordion": null,
          "id": "beraknatnedkomstdatum",
          "minDate": "2024-02-14",
          "maxDate": "2025-02-14"
        },
        "value": {
          "type": "DATE",
          "type": "DATE",
          "id": "beraknatnedkomstdatum",
          "date": "2024-02-15"
        },
        "validation": [
          {
            "type": "MANDATORY_VALIDATION",
            "type": "MANDATORY_VALIDATION",
            "questionId": "FRG_1",
            "expression": "$beraknatnedkomstdatum"
          }
        ],
        "validationError": null,
        "style": null,
        "visible": null
      },
      "KAT_1": {
        "id": "KAT_1",
        "parent": null,
        "index": 1,
        "config": {
          "type": "CATEGORY",
          "type": "CATEGORY",
          "header": null,
          "label": null,
          "icon": null,
          "text": "Beräknat nedkomstdatum",
          "description": null,
          "accordion": null
        },
        "value": null,
        "validation": [],
        "validationError": null,
        "style": null,
        "visible": null
      }
    },
    "links": [
      {
        "type": "READ_CERTIFICATE",
        "name": null,
        "description": null,
        "body": null,
        "enabled": true,
        "title": null
      },
      {
        "type": "EDIT_CERTIFICATE",
        "name": null,
        "description": null,
        "body": null,
        "enabled": true,
        "title": null
      }
    ]
  }
}

### Delete certificate
DELETE http://localhost:18030/api/certificate/640de5cb-d99b-437c-bb9a-296107f4efc9/0
Content-Type: application/json

{
  "user": {
    "id": "TSTNMT2321000156-DRAA",
    "name": "Alja Doctor",
    "role": "DOCTOR",
    "blocked": "false"
  },
  "unit": {
    "id": "TSTNMT2321000156-ALHM",
    "name": "Alfa Hudmottagningen",
    "address": "Alfaadressen 1",
    "city": "Alfastaden",
    "zipCode": "Alfapostnummer",
    "inactive": "false"
  },
  "careUnit": {
    "id": "TSTNMT2321000156-ALMC",
    "name": "Alfa Medicincentrum"
  },
  "careProvider": {
    "id": "TSTNMT2321000156-ALFA",
    "name": "Alfa Regionen"
  },
  "patient": {
    "id": {
      "type": "PERSONAL_IDENTITY_NUMBER",
      "id": "191212121212"
    },
    "firstName": "Tolvan",
    "middleName": "TP",
    "lastName": "Tolvansson",
    "fullName": "Tolvan TP Tolvansson",
    "deceased": "false",
    "protectedPerson": "false",
    "testIndicated": "false"
  }
}