### Get pdf for certificate
POST http://localhost:18030/internalapi/certificate/dbcd9c18-443c-42d5-b459-f6fec6cd9cb3/pdf
Content-Type: application/json

### Get certificate pdf
POST http://localhost:18030/api/certificate/dbcd9c18-443c-42d5-b459-f6fec6cd9cb3/pdf
Content-Type: application/json

#x-trace-id: "thisIsTraceId"
#x-session-id: "thisIsSessionId"

{
  "user": {
    "id": "TSTNMT2321000156-DRAA",
    "firstName": "Ajla",
    "lastName": "Doctor",
    "role": "DOCTOR",
    "paTitles": [],
    "specialities": [],
    "blocked": "false"
  },
  "unit": {
    "id": "TSTNMT2321000156-ALMC",
    "name": "Alfa Hudmottagningen",
    "address": "Alfaadressen 1",
    "city": "Alfastaden",
    "zipCode": "Alfapostnummer",
    "workplaceCode": "1627",
    "inactive": "false"
  },
  "careUnit": {
    "id": "TSTNMT2321000156-ALMC",
    "name": "Alfa Medicincentrum"
  },
  "careProvider": {
    "id": "TSTNMT2321000156-ALFA",
    "name": "Alfa Regionen"
  },
  "patient": {
    "id": {
      "type": "PERSONAL_IDENTITY_NUMBER",
      "id": "191212121212"
    },
    "firstName": "Tolvan",
    "middleName": "TP",
    "lastName": "Tolvansson",
    "fullName": "Tolvan TP Tolvansson",
    "deceased": "false",
    "protectedPerson": "false",
    "testIndicated": "false",
    "street": "",
    "zipcode": "",
    "city": ""
  }
}