### Create certificate - Hudmottagningen
POST http://localhost:18030/api/message
Content-Type: application/json

{
  "id": "xxxxx-yyyyy-zzzzz",
  "referenceId": "This is a ref id!",
  "certificateId": "2446aff9-c75f-41f7-ae97-0235ffeee1b3",
  "type": "KOMPLT",
  "sentBy": "FK",
  "sent": "2024-05-01T12:01:15",
  "personId": {
    "id": "191212121212",
    "type": "COORDINATION_NUMBER"
  },
  "contactInfo": ["info1", "info2"],
  "subject": "Komplettera mera!",
  "content": "Detta är en kompletteringsbegäran!",
  "complements": [
    {
      "questionId": "55",
      "content": "Ni måste komplettera denna fråga!"
    }
  ]
}
