### Get certificates for patient - Same careunit
POST http://localhost:18030/api/patient/certificates
Content-Type: application/json

{
  "user": {
    "id": "TSTNMT2321000156-DRAA",
    "name": "Alja Doctor",
    "role": "DOCTOR",
    "blocked": "false"
  },
  "unit": {
    "id": "TSTNMT2321000156-ALMC",
    "name": "Alfa Hudmottagningen",
    "address": "Alfaadressen 1",
    "city": "Alfastaden",
    "zipCode": "Alfapostnummer",
    "inactive": "false"
  },
  "careUnit": {
    "id": "TSTNMT2321000156-ALMC",
    "name": "Alfa Medicincentrum"
  },
  "careProvider": {
    "id": "TSTNMT2321000156-ALFA",
    "name": "Alfa Regionen"
  },
  "patient": {
    "id": {
      "type": "PERSONAL_IDENTITY_NUMBER",
      "id": "191212121212"
    },
    "firstName": "Tolvan",
    "middleName": "TP",
    "lastName": "Tolvansson",
    "fullName": "Tolvan TP Tolvansson",
    "deceased": "false",
    "protectedPerson": "false",
    "testIndicated": "false"
  }
}

### Get certificates for patient - Same subunit
POST http://localhost:18030/api/patient/certificates
Content-Type: application/json

{
  "user": {
    "id": "TSTNMT2321000156-DRAA",
    "name": "Alja Doctor",
    "role": "DOCTOR",
    "blocked": "false"
  },
  "unit": {
    "id": "TSTNMT2321000156-ALAM",
    "name": "Alfa Allergimottagningen",
    "address": "Alfaadressen 1",
    "city": "Alfastaden",
    "zipCode": "Alfapostnummer",
    "inactive": "false"
  },
  "careUnit": {
    "id": "TSTNMT2321000156-ALMC",
    "name": "Alfa Medicincentrum"
  },
  "careProvider": {
    "id": "TSTNMT2321000156-ALFA",
    "name": "Alfa Regionen"
  },
  "patient": {
    "id": {
      "type": "PERSONAL_IDENTITY_NUMBER",
      "id": "191212121212"
    },
    "firstName": "Tolvan",
    "middleName": "TP",
    "lastName": "Tolvansson",
    "fullName": "Tolvan TP Tolvansson",
    "deceased": "false",
    "protectedPerson": "false",
    "testIndicated": "false"
  }
}