### Create certificate
POST http://localhost:18030/testability/certificate
Content-Type: application/json

{
  "user": {
    "id": "TSTNMT2321000156-DRAA",
    "name": "Alja Doctor",
    "role": "DOCTOR",
    "blocked": "false",
    "allowCopy": "true",
    "paTitles": [],
    "specialities": [],
    "healthCareProfessionalLicence": ["Läkare"]
  },
  "unit": {
    "id": "TSTNMT2321000156-ALHM",
    "name": "Alfa Hudmottagningen",
    "address": "Alfaadressen 1",
    "city": "Alfastaden",
    "zipCode": "Alfapostnummer",
    "inactive": "false"
  },
  "careUnit": {
    "id": "TSTNMT2321000156-ALMC",
    "name": "Alfa Medicincentrum"
  },
  "careProvider": {
    "id": "TSTNMT2321000156-ALFA",
    "name": "Alfa Regionen"
  },
  "patient": {
    "id": {
      "type": "PERSONAL_IDENTITY_NUMBER",
      "id": "191212121212"
    },
    "firstName": "Tolvan",
    "middleName": "TP",
    "lastName": "Tolvansson",
    "fullName": "Tolvan TP Tolvansson",
    "deceased": "false",
    "protectedPerson": "false",
    "testIndicated": "false"
  },
  "certificateModelId": {
    "type": "fk7472",
    "version": "1.0"
  },
  "status": "SIGNED",
  "fillType": "MAXIMAL"
}

### Create certificate
DELETE http://localhost:18030/testability/certificate
Content-Type: application/json

{
  "certificateIds": [
    "1044b6f0-1349-419c-a78c-bacc592d56ae",
    "0c7eb0f2-586d-41a3-b925-bff1b101be66",
    "daaf645e-bbae-4692-b007-1b11cd6a3666"
  ]
}