package se.inera.intyg.certificateservice.domain.action.certificate.model;

public enum CertificateActionType {
  CREATE, READ, UPDATE, DELETE, SIGN, SEND, PRINT, REVOKE, REPLACE, REPLACE_CONTINUE, RENEW,
  SEND_AFTER_SIGN, SEND_AFTER_COMPLEMENT, COMPLEMENT, CANNOT_COMPLEMENT, MESSAGES, MESSAGES_ADMINISTRATIVE, FORWARD_MESSAGE,
  HANDLE_COMPLEMENT, RECEIVE_COMPLEMENT, RECEIVE_QUESTION, RECEIVE_ANSWER, RECEIVE_REMINDER,
  CREATE_MESSAGE, ANSWER_MESSAGE, SAVE_MESSAGE, DELETE_MESSAGE, SEND_MESSAGE, SAVE_ANSWER, DELETE_ANSWER,
  SEND_ANSWER, HANDLE_MESSAGE, FORWARD_CERTIFICATE, READY_FOR_SIGN, LIST_CERTIFICATE_TYPE, QUESTIONS_NOT_AVAILABLE,
  FORWARD_CERTIFICATE_FROM_LIST, FMB, SRS_DRAFT, SRS_SIGNED, CREATE_DRAFT_FROM_CERTIFICATE, UPDATE_DRAFT_FROM_CERTIFICATE,
  INACTIVE_CERTIFICATE_MODEL
}