package se.inera.intyg.certificateservice.application.certificate.dto.value;

public enum CertificateDataValueType {
  DATE, TEXT, DATE_RANGE, DATE_RANGE_LIST, DATE_LIST, CODE, BOOLEAN, DIAGNOSIS_LIST, DIAGNOSIS,
  MEDICAL_INVESTIGATION, MEDICAL_INVESTIGATION_LIST, CODE_LIST, VISUAL_ACUITY, VISUAL_ACUITIES,
  DOUBLE, INTEGER, ICF
}