package se.inera.intyg.certificateservice.application.certificate.dto;

public enum CertificateEventTypeDTO {
  CREATED,
  DELETED,
  LOCKED,
  READY_FOR_SIGN,
  SIGNED,
  SENT,
  AVAILABLE_FOR_PATIENT,
  INCOMING_MESSAGE,
  INCOMING_MESSAGE_HANDLED,
  OUTGOING_MESSAGE,
  OUTGOING_MESSAGE_HANDLED,
  INCOMING_MESSAGE_REMINDER,
  INCOMING_ANSWER,
  REQUEST_FOR_COMPLEMENT,
  REVOKED,
  REPLACED,
  REPLACES,
  COMPLEMENTS,
  COMPLEMENTED,
  EXTENDED,
  CREATED_FROM,
  COPIED_BY,
  COPIED_FROM,
  RELATED_CERTIFICATE_REVOKED
}
