package se.inera.intyg.certificateservice.application.certificate.dto.config;

public enum CertificateDataConfigType {
  CATEGORY, UE_DATE, UE_TEXTAREA, UE_CHECKBOX_DATE_RANGE_LIST, UE_CHECKBOX_MULTIPLE_DATE,
  UE_RADIO_MULTIPLE_CODE, UE_RADIO_BOOLEAN, UE_MESSAGE, UE_DIAGNOSES, UE_TEXTFIELD, UE_INTEGER,
  UE_MEDICAL_INVESTIGATION, UE_CHECKBOX_MULTIPLE_CODE, UE_VISUAL_ACUITY, UE_DROPDOWN, UE_DATE_RANGE,
  UE_CHECKBOX_BOOLEAN, UE_ICF
}
